name: Changed column

on: projects_v2

jobs:
  changed_col:
    runs-on: ubuntu-latest

    steps:
      - env:
          EVENT_CONTEXT: ${{ toJSON(github.event) }}
        run: |
          echo $EVENT_CONTEXT
